// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJYMraZuzPvwGZABAhVdVaiTkvSiYirqE',
    appId: '1:901861657949:web:6eef7b5b823c584ee8acb4',
    messagingSenderId: '901861657949',
    projectId: 'artisan-connect-app-ed066',
    authDomain: 'artisan-connect-app-ed066.firebaseapp.com',
    storageBucket: 'artisan-connect-app-ed066.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZVzfqWN3iudaeyQTBsykl997wkVfNzIA',
    appId: '1:901861657949:ios:19dae5e6bf584134e8acb4',
    messagingSenderId: '901861657949',
    projectId: 'artisan-connect-app-ed066',
    storageBucket: 'artisan-connect-app-ed066.firebasestorage.app',
    iosBundleId: 'com.example.artisanConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZVzfqWN3iudaeyQTBsykl997wkVfNzIA',
    appId: '1:901861657949:ios:19dae5e6bf584134e8acb4',
    messagingSenderId: '901861657949',
    projectId: 'artisan-connect-app-ed066',
    storageBucket: 'artisan-connect-app-ed066.firebasestorage.app',
    iosBundleId: 'com.example.artisanConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJYMraZuzPvwGZABAhVdVaiTkvSiYirqE',
    appId: '1:901861657949:web:7762721b0b7879d1e8acb4',
    messagingSenderId: '901861657949',
    projectId: 'artisan-connect-app-ed066',
    authDomain: 'artisan-connect-app-ed066.firebaseapp.com',
    storageBucket: 'artisan-connect-app-ed066.firebasestorage.app',
  );
}
